GLFW: Include missing header
It seems the header <cstdint> was missing, causing the code to fail to
compile on my system (Ubuntu 17.10 with g++ 7.2.0).

The error below occurred during compilation:

imgui-node-editor/Examples/Common/Application/Source/GLFW/Entry.cpp:70:64:
error: ‘intptr_t’ in namespace ‘std’ does not name a type

This commit fixes the above error.